common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "common"



from django.contrib.auth.views import LoginView,LogoutView
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.debug import sensitive_post_parameters
from django.http import HttpResponseRedirect,HttpResponse

class DangerousLoginView(LoginView):
    '''A LoginView with no CSRF protection.'''

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_exempt)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            print("redirect_to:",redirect_to)
            if redirect_to == self.request.path:
                raise ValueError(
                    'Redirection loop for authenticated user detected. Check that '
                    'your LOGIN_REDIRECT_URL doesn\'t point to a login page.')
            return HttpResponseRedirect(redirect_to)
        return super(LoginView, self).dispatch(request, *args, **kwargs)


class DangerousLogoutView(LogoutView):
    '''A LoginView with no CSRF protection.'''
    @method_decorator(csrf_exempt)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

from django.contrib.auth import views as auth_views
urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', DangerousLoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', DangerousLogoutView.as_view(), name='logout'),
    path('auto/', views.AppLogin.as_view(), name='auto'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from chat.views import Notification, Home
urlpatterns = [
    path("",Home.as_view()),
    path('common/', include('common.urls'),name='common'),
    path('sports/', include('sports.urls'),name='sports'),
    path("admin/", admin.site.urls),
    path('notification/', Notification.as_view())
]

sports/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'sports'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<str:sport_name>/', views.detail, name='detail'),
    path('upload/', views.Upload.as_view(), name='upload'),
    path('get_checkbox/', views.get_checkbox, name='get_checkbox'),

]

sports/models.py
from django.db import models

# Create your models here.

class TypeInfo(models.Model):
    sport_name = models.CharField(max_length=20, null=False)
    country_name = models.CharField(max_length=20, null=False)
    league_name = models.CharField(max_length=20, null=False)

class ScoreInfo(models.Model):
    sport_name = models.CharField(max_length=20, null=False)
    country_name = models.CharField(max_length=20, null=False)
    league_name = models.CharField(max_length=20, null=False)
    score = models.CharField(max_length=20, null=False)


class GameInfo(models.Model):
    unique_key = models.CharField(max_length=200, null=False,unique=True)
    sport_name = models.CharField(max_length=20, null=False)
    country_name = models.CharField(max_length=20, null=False)
    league_name = models.CharField(max_length=20, null=False)
    game_time = models.CharField(max_length=20, null=False)
    betting_result = models.CharField(max_length=4, null=False)
    home = models.CharField(max_length=20, null=False)
    home_count = models.IntegerField(null=True, default=None)
    away = models.CharField(max_length=20, null=False)
    away_count = models.IntegerField(null=True, default=None)
    home_away_win = models.FloatField(null=True,default=None)
    home_away_tie = models.FloatField(null=True,default=None)
    home_away_lose = models.FloatField(null=True,default=None)
    class Meta:
        db_table = 'gameinfo'
        verbose_name = '게임정보'

class UnoverInfo(models.Model):
    unique_key = models.CharField(max_length=200, null=False)
    sport_name = models.CharField(max_length=20, null=False)
    country_name = models.CharField(max_length=20, null=False)
    league_name = models.CharField(max_length=20, null=False)
    game_score = models.IntegerField(null=False, default=0)  # 홈-어웨이 골 합계
    score = models.CharField(max_length=20, null=False)  # 기준점
    over = models.FloatField(null=True, default=None)
    under = models.FloatField(null=True, default=None)
    unover_result = models.CharField(max_length=7, null=False)

sports/views.py
from django.shortcuts import render, redirect,HttpResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from .models import GameInfo, UnoverInfo, TypeInfo,ScoreInfo
from decimal import Decimal as dcm
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator


# Create your views here.
@csrf_exempt
def get_checkbox(request):
    print('aaaaaaaaaaaaaaaaaaaaaaaaa')
    if request.GET:
        try:
            print(request.GET)
            query_dict = dict(request.GET)
            req_type = query_dict['request_type']
            sport_name = query_dict['sport_name'][0].lower()
            if not 'ch' in query_dict:
                print(sport_name)
                type_list = TypeInfo.objects.filter(sport_name=sport_name).values()
                score_list = ScoreInfo.objects.filter(sport_name=sport_name).all().values()
                print('score_list:', score_list)
                score_set = set()
                for score_info in score_list:
                    score_set.add(dcm(score_info['score']))
                score_list = list(score_set)
                score_list.sort()
                return render(request, 'sports/sports_detail.html', {'type_list': type_list, 'sport_name': sport_name, 'score_list': score_list})
            ch = query_dict['ch']
            print('--------')
            print(req_type)
            print(ch)
            print('---------')
            if req_type[0] == '배당 조회':
                win_odds = float(query_dict['win_odds'][0])
                try:
                    tie_odds = float(query_dict['tie_odds'][0])
                except:
                    tie_odds = 0
                lose_odds = float(query_dict['lose_odds'][0])
                gap_odds = float(query_dict['gap_odds'][0])
                ignore_tie = False
                if tie_odds == 0:
                    ignore_tie = True
                value_list = []
                for info in ch:
                    print('info:',info)
                    inf = info.split('%')
                    country = inf[0]
                    print('country:',country)
                    league = inf[1]
                    print('league:',league)
                    if ignore_tie:
                        value = list(GameInfo.objects.filter(
                            country_name=country,
                            league_name=league,
                            home_away_win__gte=win_odds - gap_odds,
                            home_away_win__lte=win_odds + gap_odds,
                            home_away_lose__gte=lose_odds - gap_odds,
                            home_away_lose__lte=lose_odds + gap_odds,
                        ).values())
                    else:
                        value = list(GameInfo.objects.filter(
                            country_name=country,
                            league_name=league,
                            home_away_win__gte=win_odds - gap_odds,
                            home_away_win__lte=win_odds + gap_odds,
                            home_away_lose__gte=lose_odds - gap_odds,
                            home_away_lose__lte=lose_odds + gap_odds,
                            home_away_tie__gte = tie_odds - gap_odds,
                            home_away_tie__lte = tie_odds + gap_odds,
                        ).values())
                    value_list.extend(value)
                print('value_list:',value_list)
                total_win = 0
                total_tie = 0
                total_lose = 0
                for result in value_list:
                    if result['betting_result'] == 'home':
                        total_win +=1
                    elif result['betting_result'] == 'tie':
                        total_tie += 1
                    elif result['betting_result'] == 'away':
                        total_lose += 1
                total_added = total_win+total_tie+total_lose
                percent_win = 0
                percent_tie = 0
                percent_lose = 0
                if total_added != 0:
                    percent_win = total_win/total_added*100
                    percent_tie = total_tie / total_added * 100
                    percent_lose = total_lose / total_added * 100
                result_dict = {'win':f"{total_win}({percent_win:.1f}%)",'tie':f"{total_tie}({percent_tie:.1f}%)",'lose':f"{total_lose}({percent_lose:.1f}%)"}
                return render(request, 'sports/odds_result.html', {'total': result_dict,'result_list':value_list})
            elif req_type[0] == '언오버 조회':
                over = float(query_dict['over_unover'][0])
                score = query_dict['score'][0]
                under = float(query_dict['under_unover'][0])
                unover_gap = float(query_dict['gap_unover'][0])
                value_list = []
                for info in ch:
                    print('info:', info)
                    inf = info.split('%')
                    country = inf[0]
                    print('country:', country)
                    league = inf[1]
                    print('league:', league)
                    value = list(UnoverInfo.objects.filter(
                        country_name=country,
                        league_name=league,
                        score=score,
                        over__gte=over - unover_gap,
                        over__lte=over + unover_gap,
                        under__gte=under - unover_gap,
                        under__lte=under + unover_gap,
                    ).values())
                    value_list.extend(value)
                total_searched = len(value_list)
                total_under = 0
                total_over = 0
                total_target = 0
                added_game_score = 0
                for result in value_list:
                    if result['unover_result'] == 'under':
                        total_under +=1
                    elif result['unover_result'] == 'over':
                        total_over += 1
                    elif result['unover_result'] == 'target':
                        total_target += 1
                    added_game_score += result['game_score']
                total_added = total_under + total_over + total_target
                percent_under = 0
                percent_over = 0
                percent_target = 0
                if total_added != 0:
                    percent_under = total_under / total_added * 100
                    percent_over = total_over / total_added * 100
                    percent_target = total_target / total_added * 100
                input_dict = {'over':over, 'score':score, 'under':under}
                avg_game_score = f'{added_game_score/total_searched:.2f}'
                result_dict = {'over': f"{total_over}({percent_over:.1f}%)", 'target': f"{total_target}({percent_target:.1f}%)", 'under': f"{total_under}({percent_under:.1f}%)"}
                return render(request, 'sports/unover_result.html', {'total': result_dict,'input':input_dict, 'total_searched': total_searched,'avg_game_score':avg_game_score})
        except:
            pass
    type_list = TypeInfo.objects.all().values()
    sport_name_list = list(set([x['sport_name'][0].upper() + x['sport_name'][1:] for x in type_list]))
    return render(request, 'sports/sports_index.html', {'sport_name_list': sport_name_list})

def detail(request,sport_name):
    if '하키' == sport_name:
        sport_name = 'Hockey'
    elif '농구' == sport_name:
        sport_name = 'Basketball'
    elif '야구' == sport_name:
        sport_name = 'Baseball'
    elif '축구' == sport_name:
        sport_name = 'Football'
    sport_name=sport_name.lower()
    type_list = TypeInfo.objects.filter(sport_name=sport_name).values()
    score_list = ScoreInfo.objects.filter(sport_name=sport_name).all().values()
    print('score_list:',score_list)
    score_set = set()
    for score_info in score_list:
        score_set.add(dcm(score_info['score']))
    score_list = list(score_set)
    score_list.sort()
    return render(request, 'sports/sports_detail.html', {'type_list':type_list,'sport_name':sport_name,'score_list':score_list})

def index(request):
    type_list = TypeInfo.objects.all().values()
    print(type_list)
    sport_name_list = list(set([x['sport_name'][0].upper()+x['sport_name'][1:] for x in type_list]))
    # for i in type_list:
    #     value_list.append(i.values())
    print(sport_name_list)

    kr_sport_name_list = []
    for en_sport_name in sport_name_list:
        if 'Hockey' == en_sport_name:
            kr_sport_name_list.append('하키')
        elif 'Basketball' == en_sport_name:
            kr_sport_name_list.append('농구')
        elif 'Baseball' == en_sport_name:
            kr_sport_name_list.append('야구')
        elif 'Football' == en_sport_name:
            kr_sport_name_list.append('축구')



    return render(request, 'sports/sports_index.html',{'sport_name_list':kr_sport_name_list})


class Upload(APIView):
    def post(self, request):
        sport_name = request.data.get('sport_name', '')
        country_name = request.data.get('country_name', '')
        league_name = request.data.get('league_name', '')
        game_time = request.data.get('game_time', '')
        betting_result = request.data.get('betting_result', '')
        home = request.data.get('home', '')
        home_count = request.data.get('home_count', None)
        away = request.data.get('away', '')
        away_count = request.data.get('away_count', None)
        home_away_win = request.data.get('home_away_win', '')
        home_away_tie = request.data.get('home_away_tie', '')
        home_away_lose = request.data.get('home_away_lose', '')

        unover_info = request.data.get('unover_info', {})

        unique_key = sport_name + country_name + league_name + home + away + game_time

templates/sports/odds_result.html
{% extends 'base.html' %}
{% block content %}

<div class="mx-2 mt-5">
    <button class="d-flex justify-content-center btn btn-primary btn-rounded w-100 mt-2" onclick="javascript:history.go(-1);">이전</button>
</div>

<div class="d-flex justify-content-center">
    <div class="mt-5 align-bottom " style="vertical-align:bottom;">
        <span class="fs-3" style="vertical-align:bottom;">
            결과 값 합산:
        </span>
        <div>
            <span class="fs-1 ms-5 text-danger">
                {{ total.win }}
            </span>
            <span class="fs-3">승</span>
        </div>
        <div>
            <span class="fs-1 ms-5">
                {{ total.tie }}
            </span>
            <span class="fs-3">무</span>
        </div>
        <div>
            <span class="fs-1 ms-5 text-primary">
                {{ total.lose }}
            </span>
            <span class="fs-3">패</span>
        </div>
    </div>
</div>
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>일시</th>
            <th>국가</th>
            <th>리그</th>
            <th>홈팀</th>
            <th>홈득</th>
            <th>원정득</th>
            <th>원정팀</th>
            <th>승</th>
            <th>무</th>
            <th>패</th>
            <th>배팅결과</th>

        </tr>
        </thead>
        <tbody>
        {% if result_list %}
        {% for result in result_list %}
        <tr>
            <td>{{ result.game_time }}</td>
            <td>{{ result.country_name }}</td>
            <td>{{ result.league_name }}</td>
            <td>{{ result.home }}</td>
            <td>{{ result.home_count }}</td>
            <td>{{ result.away_count }}</td>
            <td>{{ result.away }}</td>
            <td>{{ result.home_away_win }}</td>
            <td>{{ result.home_away_tie }}</td>
            <td>{{ result.home_away_lose }}</td>
            <td>{{ result.betting_result }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">데이터가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/sports/sports_detail.html
{% extends 'base.html' %}
{% block content %}
<style>
    .input-container {
	display: grid;
	grid-template-columns: 1fr;
	grid-template-rows:  1fr 1fr;
	margin: 0 auto;
	max-width: 95%;
	}
	.input-class{
	margin: auto;
	}

</style>
<div class="mx-2">
    <button class="d-flex justify-content-center btn btn-primary btn-rounded w-100 mt-2" onclick="location.href='{% url 'sports:index' %}'">이전(종목 선택)</button>
</div>

<div class="d-flex justify-content-center">
    <div class="mt-5 align-bottom " style="vertical-align:bottom;">
        <span class="fs-3" style="vertical-align:bottom;">
            스포츠 배당 조회
        </span>
    </div>
</div>

<form action="{% url 'sports:get_checkbox' %}" method="get" enctype="multipart/form-data" id="input_form">
    <input type="hidden" name="sport_name" value="{{ sport_name }}">
    <div class="mx-2  mt-4 border rounded-3">
        <div class="mb-3 input-container mt-3">
            <span class="input-class" style="display:flex; flex-direction: row; justify-content: center; align-items: center">
                <label class="mx-1" for="win_odds" style="white-space: nowrap;">승</label>
                <input type="number" step=0.01 class="form-control" style="font-size:12px; padding-left:0px; padding-right:0px;" name="win_odds" id="win_odds" oninput="inputChanged()" min="0" value="win_odds">
                <label class="mx-1 ms-3" for="tie_odds" style="white-space: nowrap;">무(0일시 조회X)</label>
                <input type="number" step=0.01 class="form-control" style="font-size:12px; padding-left:0px; padding-right:0px;" name="tie_odds" id="tie_odds" oninput="inputChanged()" min="0" value="tie_odds">
                <label class="mx-1 ms-3" for="lose_odds" style="white-space: nowrap;">패</label>
                <input type="number" step=0.01 class="form-control" style="font-size:12px; padding-left:0px; padding-right:0px;" name="lose_odds" id="lose_odds" oninput="inputChanged()" min="0" value="lose_odds">
                <label class="mx-1 ms-3" for="gap_odds" style="white-space: nowrap;">오차</label>
                <input type="number" step=0.01 class="form-control" style="font-size:12px; padding-left:0px; padding-right:0px;" name="gap_odds" id="gap_odds" oninput="inputChanged()" min="0" value="gap_odds">
            </span>
            <input class="d-flex justify-content-center btn btn-primary btn-rounded w-100 mt-2" name="request_type" type="submit" value="배당 조회">
        </div>
    </div>
    <div class="mx-2  mt-4 border rounded-3">
        <div class="mb-3 input-container mt-3">
            <span class="input-class" style="display:flex; flex-direction: row; justify-content: center; align-items: center">
                <label class="mx-1" for="over_unover" style="white-space: nowrap;">오버</label>
                <input type="number" step=0.01 class="form-control" style="font-size:12px; padding-left:0px; padding-right:0px;" name="over_unover" id="over_unover" oninput="inputChanged()" min="0" value="win_odds">

                {% if score_list %}
                <label class="mx-1 ms-3" for="score_unover" style="white-space: nowrap;">기준점</label>
<!--                <input type="number" class="form-control" style="font-size:12px; padding-left:0px; padding-right:0px;" name="score_unover" id="score_unover" oninput="inputChanged()" min="0" value="tie_odds">-->
                <select name="score"  class="form-select" form="input_form" id="score_unover">
                {% for score in score_list %}
                <option value="{{ score }}">{{ score }}</option>
                    {% endfor %}
                </select>

                {% else %}
                {% endif %}
                <label class="mx-1 ms-3" for="under_unover" style="white-space: nowrap;">언더</label>
                <input type="number" step=0.01 class="form-control" style="font-size:12px; padding-left:0px; padding-right:0px;" name="under_unover" id="under_unover" oninput="inputChanged()" min="0" value="lose_odds">
                <label class="mx-1 ms-3" for="gap_unover" style="white-space: nowrap;">오차</label>
                <input type="number" step=0.01 class="form-control" style="font-size:12px; padding-left:0px; padding-right:0px;" name="gap_unover" id="gap_unover" oninput="inputChanged()" min="0" value="gap_odds">
            </span>
            <input class="d-flex justify-content-center btn btn-primary btn-rounded w-100 mt-2" name="request_type" type="submit" value="언오버 조회">
        </div>
    </div>


    <div class="mt-2">
        <table class="table">
            <thead>
            <tr class="table-dark">
                <th>선택</th>
                <th>국가</th>
                <th>리그</th>
            </tr>
            </thead>
            <tbody>
            {% if type_list %}
            {% for type in type_list %}
            <tr>
                <td><input type="checkbox" name="ch" value="{{ type.country_name }}%{{ type.league_name }}"></td>
                <td>{{ type.country_name }}</td>
                <td>{{ type.league_name }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">데이터가 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
</form>

{% endblock %}

templates/sports/sports_index.html
{% extends 'base.html' %}
{% block content %}
<style>
    .sports-button-container {
	display: grid;
	grid-template-columns: 1fr 1fr;
	}

</style>
<div class="d-flex justify-content-center">
    <div class="mt-5 align-bottom " style="vertical-align:bottom;">
        <span class="fs-3" style="vertical-align:bottom;">
            종목 선택
        </span>
    </div>
</div>
<div class="container show-grid">
    <div class="row">
        {% if sport_name_list %}
        {% for sport_name in sport_name_list %}
        <div class="col-md-6 mt-5">
            <button class="btn btn-primary btn-lg w-100 mt-2" onclick="location.href='{% url 'sports:detail' sport_name %}?fail='">
                {{ sport_name }}
            </button>
        </div>
        {% endfor %}
        {% else %}
        데이터가 없습니다.
        {% endif %}
    </div>
</div>
{% endblock %}

templates/sports/unover_result.html
{% extends 'base.html' %}
{% block content %}
<div class="mx-2 mt-5">
    <button class="d-flex justify-content-center btn btn-primary btn-rounded w-100 mt-2" onclick="javascript:history.go(-1);">이전</button>
</div>

<div class="d-flex justify-content-center">
    <div class="mt-5 me-5" style="">
        <span class="fs-3" style="vertical-align:bottom;">
            검색값:
        </span>
        <div>
            <span class="fs-3 text-start">오버:</span>
            <span class="fs-1 text-end text-danger">
                {{ input.over }}
            </span>

        </div>
        <div>
            <span class="fs-3 text-start">기준점:</span>
            <span class="fs-1 text-end">
                {{ input.score }}
            </span>

        </div>
        <div>
            <span class="fs-3 text-start">언더:</span>
            <span class="fs-1 text-end text-primary">
                {{ input.under }}
            </span>

        </div>
    </div>
    <div class="mt-3" style="">
        <div>
            <span class="fs-3">검색 결과:</span>
            <span class="fs-1 ms-5 text-danger">
                {{ total_searched }}
            </span>
            <span class="fs-3">개</span>
        </div>
        <div>
            <span class="fs-3">평균 득점:</span>
            <span class="fs-1">
                {{ avg_game_score }}
            </span>
        </div>
        <div>
            <span class="fs-3">오버:</span>
            <span class="fs-1 text-danger">
                {{ total.over }}
            </span>
        </div>
        <div>
            <span class="fs-3">언더:</span>
            <span class="fs-1 text-primary">
                {{ total.under }}
            </span>
        </div>
        <div>
            <span class="fs-3">적특:</span>
            <span class="fs-1 ">
                {{ total.target }}
            </span>
        </div>
    </div>
</div>
{% endblock %}